language: node_js
node_js:
    - "4"    

install:
    - npm install -g gulp-cli
    - npm install
    - npm run tsd-reinstall
    
script:
    - npm run lint
    - npm test
    - npm run build

before_deploy: "echo 'Deploying: start'"

deploy:
    provider: npm
    email: "igba14@gmail.com"
    api_key: "25ab4bb9-cb67-45d5-b9bd-b4665715e12d"
    
after_deploy: "echo 'Deploying: finish'"
    